---
name: lint
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request: {}

permissions:
  contents: read

jobs:

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: composer install
      - run: ./vendor/bin/phpunit

  phpunit-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: [mariadb, pgsql]
    env:
      TEST_DATABASE: ${{ matrix.database }}
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: pdo_mysql, pdo_pgsql
      - run: composer install
      - run: ./vendor/bin/phpunit --testsuite Integration

  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.5]
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: composer install
      - run: ./vendor/bin/php-cs-fixer fix --dry-run --sequential
